### ISSUE TITLE
date_histogram转换DSL有问题？

### ISSUE THREAD

**Issue by NMZXYCDRL** [cch123/elasticsql#13]
使用例程转换下列语句为DSL的时候，[来源](https://github.com/cch123/elasticsql/issues/4)  
`select * from table_name group by date_histogram(field='create_time', interval='1h')
`
报错
`syntax error at position 81`

interval要改成value么？

**Comment by cch123** [comment]
@NMZXYCDRL ，上游的parser最近有更新，interval大概被当函数解析了，我修改了一下，现在可以先用value替代interval
拉一下最新的代码就好
