### ISSUE TITLE
Is the example correct?

### ISSUE THREAD

**Issue by cemremengu** [cch123/elasticsql#15]
First of all thanks for the great work!

The functionality check-list mentions that `like` operator is implemented for phrase search. 

However, in the example, although the strict equality `=` is used, the generated elasticsearch query is a phrase match. In that case, as far as I understood, shouldn't it generate a term search instead?

If the example is correct, what is the way to generate a term search query?

**Comment by cch123** [comment]
If one of your fields is some text, and set to analyzed(before es 5.0, string field can be set to analyzed or not_analyzed)

And when your field is "Hello World", the inverted index will contain the terms: [Hello, World] => two terms.

And term query like the following:

```json
GET my_index/my_type/_search
{
  "query": {
    "term": {
      "field_name": "Hello World" 
    }
  }
}
```

will not match, but in our current company, the index was created before this lib born. And I want `sql =` to work with this analyzed text field, so I set equal to match_phrase(although it's still not the same as like in rdbms systems), If your field is set to not_analyzed, in fact, the match_phrase and term query are the same, I think  :-)

Also, some people recommend to change the like query function as `wild_card query`. But it's really quite slow~

These behavior can be easily changed by editing the https://github.com/cch123/elasticsql/blob/master/select_handler.go#L245

So if you think it's not working as you think, feel free to fork and modified to match your requirement~

**Comment by cemremengu** [comment]
Thank you for the detailed answer!
