### ISSUE TITLE
Large Query 

### ISSUE THREAD

**Issue by Kamelia2000** [cch123/elasticsql#17]
Hello i need to know when we make it large query have alot of join inside SQL possible to  make by your Go solution to Elastic Query match ? 

Thanks,
George

**Comment by cch123** [comment]
no, join is not supported
If your data relation is 1:1, you can put them in a single index, or use nested doc. But if not, I think this lib is not helpful

**Comment by Kamelia2000** [comment]
Do you kow any library can work in join

**Comment by cch123** [comment]
@Kamelia2000 

Maybe this slide can offer some ideas~
https://www.slideshare.net/sirensolutions/searching-relational-data-with-elasticsearch
