### ISSUE TITLE
简单查询语句报错 

### ISSUE THREAD

**Issue by EverCurse** [cch123/elasticsql#18]
select * from aaa where remote_addr="111.206.36.1" limit 10;
转换为:
{"query" : {"bool" : {"must" : [{"match" : {"remote_addr" : {"query" : "111.206.36.1", "type" : "phrase"}}}]}},"from" : 0,"size" : 10}

用该dsl语句查询的时候:
`{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "[match] query does not support [type]",
"line": 1,
"col": 84
}
],
"type": "parsing_exception",
"reason": "[match] query does not support [type]",
"line": 1,
"col": 84
},
"status": 400
}`

必须要删除 "type" : "phrase" 才行

**Comment by cch123** [comment]
@EverCurse ，看起来是6.0+的版本不支持这种语法了
如果输出从
{"query" : {"bool" : {"must" : [{"match" : {"remote_addr" : {"query" : "111.206.36.1", "type" : "phrase"}}}]}},"from" : 0,"size" : 10}
改成
{"query" : {"bool" : {"must" : [{"match_phrase" : {"remote_addr" : {"query" : "111.206.36.1"}}}]}},"from" : 0,"size" : 10}
会报错么

**Comment by EverCurse** [comment]
@cch123 这样就不会报错了 有兼容6.0+的计划吗

**Comment by cch123** [comment]
@EverCurse ，好，我先看看 match_phrase 在之前和之后的版本间有没有语义变化，要是没变化就统一改一下，有的话可能另开一个函数

**Comment by cch123** [comment]
@EverCurse ，看了看老文档里的 match type phrase 和 match_phrase 一致，我先改了一版~
已更新到 master

**Comment by EverCurse** [comment]
@cch123 感谢。需要的时候@一下随时测试。

**Comment by cch123** [comment]
@EverCurse ，我已经改了~
你如果再碰到异常再回复就好~

**Comment by EverCurse** [comment]
@cch123 感谢~

**Comment by EverCurse** [comment]
@cch123 大神原来是advanced-go-programming-book 作者呀 。👍

**Comment by cch123** [comment]
@EverCurse ，低调低调~
