### ISSUE TITLE
multi_match与match_phrase的区别

### ISSUE THREAD

**Issue by fengweiqiang** [cch123/elasticsql#19]
https://elasticsearch.cn/question/5524
你好，如果想要使用multi_match，sql应该使用什么符号进行查询？

**Comment by cch123** [comment]
目前暂时还不支持

这个好像写 sql 的时候没有相同语义的符号。。要是用其它的也挺奇怪的

我想法是扩展一下加个自定义函数？

在这里的 switch 下面加一个 *sqlparser.FuncExpr 的 case，然后写类似这种的 SQL：

```sql
select * from aaa
where a=1 
and subquery(b, 'yes we can')
```

**Comment by fengweiqiang** [comment]
嗯，谢谢，还有就是查询字段null/not null 没实现，是因为版本不兼容吗？

**Comment by cch123** [comment]
@fengweiqiang ，我们当时没这个需求，因为 es 里的数据都是从 mysql 来的，而 mysql 的规范都会要求字段不为 null

**Comment by fengweiqiang** [comment]
嗯嗯，非常感想你的讲解

**Comment by cch123** [comment]
@fengweiqiang ，在这个分支上已经支持了，你那边测测吧，要是没问题，我合 master：

https://github.com/cch123/elasticsql/tree/feature_multi_match

**Comment by cch123** [comment]
我自己简单试了试没啥问题，https://github.com/cch123/elasticsql/pull/20
之后有问题可以 reopen 或者另开 issue
