### ISSUE TITLE
is it possible to make group by every 5 minutes or somethings?

### ISSUE THREAD

**Issue by affinity226** [cch123/elasticsql#4]
elaticsearch sql have below dsl,
{
    "aggs" : {
        "articles_over_time" : {
            "date_histogram" : {
                "field" : "date",
                "interval" : "1.5h"
            }
        }
    }
}

is it possible?

**Comment by cch123** [comment]
I'll try to implement it in this weekend

**Comment by cch123** [comment]
@affinity226 
https://github.com/cch123/elasticsql/pull/5
group by date_histogram is supported now
you can use
```sql
select * from table_name group by date_histogram(field='create_time', interval='1h')
```
to generate your dsl
